### ISSUE TITLE
Can not run the programm

### ISSUE THREAD

**Issue by flyingbrike** [zmcx16/AxisTradeCult#1]
Hello
This looks very nice.
But i can not run it. Installed all dependencies is requirements .
Added setpath, but i think this is the problem
When try to run , i get this :

 pp@stmserver:~/AxisTradeCult/src$ python3 Program/__init__.py
Traceback (most recent call last):
  File "Program/__init__.py", line 6, in <module>
    import Program.GlobalVar as gv
ModuleNotFoundError: No module named 'Program'

**Comment by zmcx16** [comment]
Hi flyingbrike,

I think this problem is because the python path setting problem, it sounds
like you use Mac or Linux OS, you can follow the below steps:

1. cd src
2. export PYTHONPATH=.
3. python Program/__init__.py

If you have other problems,  kindly let me know :)

Regard,
Ken

flyingbrike <notifications@github.com> 於 2019年7月10日 週三 上午4:17寫道：
